# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Nvy < Formula
  desc "A minimalist, plugin-driven runtime version manager"
  homepage "https://github.com/trevorphillipscoding/nvy"
  version "1.4.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/trevorphillipscoding/nvy/releases/download/v1.4.0/nvy_1.4.0_macOS_x86_64.tar.gz"
      sha256 "e0d6ccc892e154c8b6eecc873794b0be6048a966088d6aa6e278a1ba976f7db7"

      define_method(:install) do
        bin.install "nvy"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/trevorphillipscoding/nvy/releases/download/v1.4.0/nvy_1.4.0_macOS_arm64.tar.gz"
      sha256 "434d0c2958058e6a99d0ecddf4407518d290ed92984e34ed866b02416a16fc30"

      define_method(:install) do
        bin.install "nvy"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/trevorphillipscoding/nvy/releases/download/v1.4.0/nvy_1.4.0_linux_x86_64.tar.gz"
      sha256 "168d5f8ccdb17b2453cdcb9ef757361322e18ee51799d1c9a942da98498a6a99"
      define_method(:install) do
        bin.install "nvy"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/trevorphillipscoding/nvy/releases/download/v1.4.0/nvy_1.4.0_linux_arm64.tar.gz"
      sha256 "ff98ea3fc5280dfb5f5d7ecb2388759c0ef4f258edfec45bd14ac6da49b98890"
      define_method(:install) do
        bin.install "nvy"
      end
    end
  end

  test do
    system "#{bin}/nvy", "--version"
  end
end
