# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Nvy < Formula
  desc "A minimalist, plugin-driven runtime version manager"
  homepage "https://github.com/trevorphillipscoding/nvy"
  version "0.1.1"
  license "MIT"

  on_macos do
    on_intel do
      url "https://github.com/trevorphillipscoding/nvy/releases/download/v0.1.1/nvy_0.1.1_macOS_x86_64.tar.gz"
      sha256 "92995aa36ff461c89413f39642f1c70b1c315319e35716b298f457f0ed28b1f6"

      def install
        bin.install "nvy"
      end
    end
    on_arm do
      url "https://github.com/trevorphillipscoding/nvy/releases/download/v0.1.1/nvy_0.1.1_macOS_arm64.tar.gz"
      sha256 "4343da48db5f7c234a81851e8bca1ea2a27d790b5c2afd7e5b4afb6f382b1ad9"

      def install
        bin.install "nvy"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/trevorphillipscoding/nvy/releases/download/v0.1.1/nvy_0.1.1_linux_x86_64.tar.gz"
        sha256 "ae06cb0ae3968035f29d24505971f317ffe2781b11514a744c529da4ac9f1d02"

        def install
          bin.install "nvy"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/trevorphillipscoding/nvy/releases/download/v0.1.1/nvy_0.1.1_linux_arm64.tar.gz"
        sha256 "00b1cb31fee8104bfb8fb5462f5ce9c0f574e227a68564f88b237b8c5f6747d7"

        def install
          bin.install "nvy"
        end
      end
    end
  end

  test do
    system "#{bin}/nvy", "--version"
  end
end
