# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Nvy < Formula
  desc "A minimalist, plugin-driven runtime version manager"
  homepage "https://github.com/trevorphillipscoding/nvy"
  version "0.1.2"
  license "MIT"

  on_macos do
    on_intel do
      url "https://github.com/trevorphillipscoding/nvy/releases/download/v0.1.2/nvy_0.1.2_macOS_x86_64.tar.gz"
      sha256 "b38c1e4421a1bc659456317c7a41a986fea8b5b990fd340e9a11c92e98f8815f"

      def install
        bin.install "nvy"
      end
    end
    on_arm do
      url "https://github.com/trevorphillipscoding/nvy/releases/download/v0.1.2/nvy_0.1.2_macOS_arm64.tar.gz"
      sha256 "5331e26aca81cd6c1603cabe9bf53ae4e29a7b34bc205cf21c9792e2b658c651"

      def install
        bin.install "nvy"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/trevorphillipscoding/nvy/releases/download/v0.1.2/nvy_0.1.2_linux_x86_64.tar.gz"
        sha256 "458a8e698890cb925b5a03b73252e0d1f6852e839a5be3ffbda8ec1e23ad586c"

        def install
          bin.install "nvy"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/trevorphillipscoding/nvy/releases/download/v0.1.2/nvy_0.1.2_linux_arm64.tar.gz"
        sha256 "137973ca7265d0b9785f7ad9c5326e60dfd07fbd1a6c596c4f28ee4eda12beaf"

        def install
          bin.install "nvy"
        end
      end
    end
  end

  test do
    system "#{bin}/nvy", "--version"
  end
end
